branch-defaults:
  default:
    environment: Udagram
    group_suffix: null
environment-defaults:
  Udagarm:
    branch: master
    repository: https://github.com/Kamal1182/nd0067-c4-deployment-process-project-starter
global:
  application_name: udagarm
  branch: null
  default_ec2_keyname: vockey
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
